description: This component creates an image representation of the generated movie
  script using OpenAI's DALL-E API. It takes the 'script_text' value from the GPT4ScriptGenerator
  component, sends it to DALL-E API with an appropriate configuration, and receives
  the generated image URL. Then, it stores the 'theme_text', 'script_text', and the
  'image_url' as output.
name: DALL-EImageGenerator
parameters: {}
